development:
  adapter: postgresql
  encoding: unicode
  database: pokemon
  pool: 2
  username: nikolaipawlowski
  password: postgres4123

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>